"""
Generate ground truth annotations for CLARA retrieval evaluation.

This script creates structured ground truth data that maps each CFR regulation
to the specific protocol sections (chunks) that address it. This enables
measuring retrieval quality (Recall@k, Precision@k, MRR, NDCG) for each
embedding strategy.

Ground truth sources:
  1. REAL PROTOCOLS: Downloaded from ClinicalTrials.gov (data/documents/compliant/).
     Sections are annotated by keyword-matching against known regulatory topics,
     producing "silver-standard" labels. A human reviewer can upgrade these to
     gold-standard by editing the output JSON.

  2. SYNTHETIC NON-COMPLIANT: Generated by redacting required elements from real
     protocols (data/documents/non_compliant/). For these, the ground truth is
     that redacted sections should NOT match the corresponding regulation (negative
     examples), while un-redacted sections retain their original annotations.

Output:
  test/ground_truth/annotations.json — list of GroundTruthSample objects:
    {
      "protocol_id": "NCT03196180",
      "source": "compliant" | "non_compliant",
      "protocol_text": "...",
      "chunks": ["chunk_0", "chunk_1", ...],
      "annotations": {
        "21 CFR Part 50": {
          "relevant_chunk_indices": [2, 5, 14],
          "relevance_scores": [2, 1, 1],   // 2=highly relevant, 1=partially, 0=irrelevant
          "description": "Informed consent, vulnerable populations"
        },
        ...
      }
    }

Usage:
    python test/generate_ground_truth.py --protocols-dir data/documents/compliant/parsed
    python test/generate_ground_truth.py --protocols-dir data/documents/compliant/parsed --include-non-compliant
"""

import json
import re
import sys
import argparse
from pathlib import Path
from typing import Optional

# ─── Regulation-to-keyword mapping ─────────────────────────────
# Each CFR part has topics and keywords that a protocol section must contain
# to be considered "relevant" to that regulation. Two tiers:
#   - STRONG keywords → relevance_score = 2 (highly relevant)
#   - WEAK keywords   → relevance_score = 1 (partially relevant)

REGULATION_ANNOTATIONS = {
    "21 CFR Part 11": {
        "description": "Electronic records; electronic signatures; audit trails; system validation",
        "strong": [
            r"electronic\s+record", r"electronic\s+signature", r"e-?signature",
            r"audit\s+trail", r"system\s+validation", r"21\s*CFR\s*(?:Part\s*)?11",
            r"part\s*11\b", r"computer\s+system\s+validation",
        ],
        "weak": [
            r"data\s+integrity", r"access\s+control", r"user\s+access",
            r"password", r"electronic\s+data", r"digital\s+signature",
            r"software\s+validation", r"data\s+entry", r"e?CRF",
            r"case\s+report\s+form", r"source\s+data\s+verification",
        ],
    },
    "21 CFR Part 50": {
        "description": "Protection of human subjects; informed consent elements and process",
        "strong": [
            r"informed\s+consent", r"21\s*CFR\s*(?:Part\s*)?50", r"part\s*50\b",
            r"consent\s+form", r"consent\s+process", r"voluntary\s+participation",
            r"right\s+to\s+withdraw", r"assent",
        ],
        "weak": [
            r"human\s+subject", r"vulnerable\s+population", r"pregnant\s+wom[ae]n",
            r"pediatric", r"children", r"minor", r"legally\s+authorized\s+representative",
            r"compensation\s+for\s+injury", r"alternative", r"risk.*benefit",
            r"confidentiality", r"privacy",
        ],
    },
    "21 CFR Part 56": {
        "description": "Institutional Review Boards: composition, review procedures, oversight",
        "strong": [
            r"institutional\s+review\s+board", r"\bIRB\b", r"21\s*CFR\s*(?:Part\s*)?56",
            r"part\s*56\b", r"ethics\s+committee", r"continuing\s+review",
            r"IRB\s+approv", r"IRB\s+review",
        ],
        "weak": [
            r"ethical\s+review", r"research\s+ethics", r"protocol\s+amendment",
            r"deviation\s+report", r"annual\s+review", r"expedited\s+review",
            r"exempt\s+review", r"quorum",
        ],
    },
    "21 CFR Part 58": {
        "description": "Good Laboratory Practice (GLP) for nonclinical laboratory studies",
        "strong": [
            r"good\s+laboratory\s+practice", r"\bGLP\b", r"21\s*CFR\s*(?:Part\s*)?58",
            r"part\s*58\b", r"nonclinical\s+(?:lab|stud)", r"preclinical\s+(?:lab|stud)",
        ],
        "weak": [
            r"laboratory\s+procedure", r"specimen\s+handling", r"quality\s+assurance\s+unit",
            r"test\s+article", r"test\s+system", r"study\s+director",
        ],
    },
    "21 CFR Part 211": {
        "description": "Current Good Manufacturing Practice (cGMP) for finished pharmaceuticals",
        "strong": [
            r"good\s+manufacturing\s+practice", r"\bcGMP\b", r"\bGMP\b",
            r"21\s*CFR\s*(?:Part\s*)?211", r"part\s*211\b",
            r"manufacturing\s+process", r"batch\s+record",
        ],
        "weak": [
            r"quality\s+control", r"drug\s+product", r"labeling",
            r"stability\s+testing", r"sterility", r"contamination",
        ],
    },
    "21 CFR Part 312": {
        "description": "Investigational New Drug (IND) application; safety reporting; sponsor responsibilities",
        "strong": [
            r"investigational\s+new\s+drug", r"\bIND\b", r"21\s*CFR\s*(?:Part\s*)?312",
            r"part\s*312\b", r"IND\s+(?:application|submission|safety)",
            r"serious\s+adverse\s+event", r"\bSAE\b", r"safety\s+report",
        ],
        "weak": [
            r"adverse\s+event", r"adverse\s+reaction", r"sponsor\s+responsibilit",
            r"investigator\s+(?:responsibilit|brochure)", r"clinical\s+hold",
            r"annual\s+report", r"drug\s+accountability", r"DSMB",
            r"data\s+(?:safety|monitoring)\s+(?:board|committee)",
        ],
    },
    "21 CFR Part 314": {
        "description": "NDA/ANDA applications for FDA approval to market a new drug",
        "strong": [
            r"new\s+drug\s+application", r"\bNDA\b", r"\bANDA\b",
            r"21\s*CFR\s*(?:Part\s*)?314", r"part\s*314\b",
        ],
        "weak": [
            r"FDA\s+approv", r"marketing\s+application", r"supplemental\s+application",
            r"bioequivalence", r"post-?market",
        ],
    },
    "45 CFR Part 46": {
        "description": "HHS Common Rule: protection of human subjects in federally funded research",
        "strong": [
            r"common\s+rule", r"45\s*CFR\s*(?:Part\s*)?46", r"part\s*46\b",
            r"HHS\s+regulation", r"federally\s+funded\s+research",
        ],
        "weak": [
            r"human\s+subject\s+protection", r"institutional\s+assurance",
            r"FWA", r"federal-?wide\s+assurance", r"OHRP",
            r"subpart\s+[A-D]", r"prisoner", r"pregnant",
        ],
    },
}


def chunk_text(text: str, chunk_size: int = 800, overlap: int = 120) -> list[str]:
    """
    Replicate the chunking strategy from vector_store.py:
    RecursiveCharacterTextSplitter(chunk_size=800, chunk_overlap=120).
    """
    separators = ["\n\n", "\n", ". ", " "]
    chunks = []

    def _split(text, seps):
        if not seps or len(text) <= chunk_size:
            return [text] if text.strip() else []
        sep = seps[0]
        parts = text.split(sep)
        result = []
        current = ""
        for part in parts:
            candidate = current + sep + part if current else part
            if len(candidate) <= chunk_size:
                current = candidate
            else:
                if current:
                    result.append(current)
                if len(part) > chunk_size:
                    result.extend(_split(part, seps[1:]))
                else:
                    current = part
        if current:
            result.append(current)
        return result

    raw_chunks = _split(text, separators)

    # Apply overlap: prepend tail of previous chunk
    final = []
    for i, chunk in enumerate(raw_chunks):
        if i > 0 and overlap > 0:
            prev_tail = raw_chunks[i - 1][-overlap:]
            chunk = prev_tail + chunk
        final.append(chunk.strip())

    return [c for c in final if c]


def annotate_chunks(
    chunks: list[str],
    regulations: dict = REGULATION_ANNOTATIONS,
) -> dict:
    """
    For each regulation, find which chunks are relevant using keyword matching.
    Returns {reg_label: {"relevant_chunk_indices": [...], "relevance_scores": [...], ...}}
    """
    annotations = {}

    for reg_label, reg_info in regulations.items():
        relevant_indices = []
        relevance_scores = []

        strong_patterns = [re.compile(p, re.IGNORECASE) for p in reg_info["strong"]]
        weak_patterns = [re.compile(p, re.IGNORECASE) for p in reg_info["weak"]]

        for idx, chunk in enumerate(chunks):
            strong_hits = sum(1 for p in strong_patterns if p.search(chunk))
            weak_hits = sum(1 for p in weak_patterns if p.search(chunk))

            if strong_hits > 0:
                relevant_indices.append(idx)
                relevance_scores.append(2)  # highly relevant
            elif weak_hits >= 2:
                # Need at least 2 weak matches to count as partially relevant
                relevant_indices.append(idx)
                relevance_scores.append(1)  # partially relevant

        annotations[reg_label] = {
            "relevant_chunk_indices": relevant_indices,
            "relevance_scores": relevance_scores,
            "description": reg_info["description"],
            "n_relevant": len(relevant_indices),
        }

    return annotations


def load_protocol_text(path: Path) -> tuple[str, str]:
    """Load protocol text and extract NCT ID from filename."""
    text = path.read_text(encoding="utf-8", errors="replace")
    # Extract NCT ID from filename pattern: NCTxxxxxxxx_...
    nct_match = re.search(r"(NCT\d{8})", path.stem)
    protocol_id = nct_match.group(1) if nct_match else path.stem
    return protocol_id, text


def generate_ground_truth(
    protocols_dir: Path,
    non_compliant_dir: Optional[Path] = None,
    output_path: Optional[Path] = None,
    limit: Optional[int] = None,
) -> list[dict]:
    """
    Generate ground truth annotations for all protocols.
    """
    samples = []

    # 1. Process compliant protocols
    if protocols_dir.exists():
        files = sorted(protocols_dir.glob("*.txt"))
        if not files:
            # Try PDF text extraction fallback
            files = sorted(protocols_dir.glob("*.pdf"))
            print(f"No .txt files found; found {len(files)} PDFs (parse them first with parse.py)")

        if limit:
            files = files[:limit]

        print(f"\n{'='*70}")
        print(f"GROUND TRUTH GENERATION — COMPLIANT PROTOCOLS")
        print(f"{'='*70}")
        print(f"Source: {protocols_dir.resolve()}")
        print(f"Protocols: {len(files)}")
        print()

        for f in files:
            protocol_id, text = load_protocol_text(f)
            chunks = chunk_text(text)
            annotations = annotate_chunks(chunks)

            # Summary
            total_relevant = sum(a["n_relevant"] for a in annotations.values())
            regs_with_hits = sum(1 for a in annotations.values() if a["n_relevant"] > 0)

            print(f"  {protocol_id:<20} chunks={len(chunks):<5} "
                  f"annotated_chunks={total_relevant:<4} "
                  f"regs_covered={regs_with_hits}/8")

            samples.append({
                "protocol_id": protocol_id,
                "source": "compliant",
                "source_file": str(f.name),
                "n_chunks": len(chunks),
                "chunks": chunks,
                "annotations": annotations,
            })

    # 2. Process non-compliant protocols (if available)
    if non_compliant_dir and non_compliant_dir.exists():
        nc_files = sorted(non_compliant_dir.glob("*.txt"))
        if limit:
            nc_files = nc_files[:limit]

        if nc_files:
            print(f"\n{'='*70}")
            print(f"GROUND TRUTH GENERATION — NON-COMPLIANT (REDACTED) PROTOCOLS")
            print(f"{'='*70}")
            print(f"Source: {non_compliant_dir.resolve()}")
            print(f"Protocols: {len(nc_files)}")
            print()

            for f in nc_files:
                protocol_id, text = load_protocol_text(f)
                chunks = chunk_text(text)
                annotations = annotate_chunks(chunks)

                total_relevant = sum(a["n_relevant"] for a in annotations.values())
                regs_with_hits = sum(1 for a in annotations.values() if a["n_relevant"] > 0)

                print(f"  {protocol_id:<20} chunks={len(chunks):<5} "
                      f"annotated_chunks={total_relevant:<4} "
                      f"regs_covered={regs_with_hits}/8")

                samples.append({
                    "protocol_id": f"{protocol_id}_redacted",
                    "source": "non_compliant",
                    "source_file": str(f.name),
                    "n_chunks": len(chunks),
                    "chunks": chunks,
                    "annotations": annotations,
                })

    # 3. Generate synthetic edge-case protocols (always available, no files needed)
    print(f"\n{'='*70}")
    print(f"GROUND TRUTH GENERATION — SYNTHETIC PROTOCOLS")
    print(f"{'='*70}")
    synthetic = _generate_synthetic_protocols()
    for s in synthetic:
        chunks = chunk_text(s["text"])
        annotations = annotate_chunks(chunks)
        total_relevant = sum(a["n_relevant"] for a in annotations.values())
        regs_with_hits = sum(1 for a in annotations.values() if a["n_relevant"] > 0)

        print(f"  {s['id']:<20} chunks={len(chunks):<5} "
              f"annotated_chunks={total_relevant:<4} "
              f"regs_covered={regs_with_hits}/8")

        samples.append({
            "protocol_id": s["id"],
            "source": "synthetic",
            "source_file": None,
            "n_chunks": len(chunks),
            "chunks": chunks,
            "annotations": annotations,
        })

    # Save
    if output_path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        # Save without full chunk text (too large); save indices and metadata only
        slim_samples = []
        for s in samples:
            slim = {k: v for k, v in s.items() if k != "chunks"}
            slim["chunk_previews"] = [c[:100] + "..." if len(c) > 100 else c for c in s["chunks"]]
            slim_samples.append(slim)

        with open(output_path, "w") as f:
            json.dump(slim_samples, f, indent=2)
        print(f"\nSaved annotations to {output_path.resolve()}")

        # Also save full version with chunks for the evaluator
        full_path = output_path.parent / "annotations_full.json"
        with open(full_path, "w") as f:
            json.dump(samples, f, indent=2)
        print(f"Saved full annotations (with chunks) to {full_path.resolve()}")

    # Summary statistics
    print(f"\n{'='*70}")
    print(f"SUMMARY")
    print(f"{'='*70}")
    print(f"Total samples:   {len(samples)}")
    print(f"  Compliant:     {sum(1 for s in samples if s['source'] == 'compliant')}")
    print(f"  Non-compliant: {sum(1 for s in samples if s['source'] == 'non_compliant')}")
    print(f"  Synthetic:     {sum(1 for s in samples if s['source'] == 'synthetic')}")
    print()

    # Per-regulation coverage
    print(f"{'Regulation':<25} {'Samples w/ hits':>15} {'Avg relevant chunks':>20}")
    print("-" * 65)
    for reg in REGULATION_ANNOTATIONS:
        samples_with = sum(
            1 for s in samples
            if s["annotations"].get(reg, {}).get("n_relevant", 0) > 0
        )
        avg_relevant = (
            sum(s["annotations"].get(reg, {}).get("n_relevant", 0) for s in samples)
            / max(len(samples), 1)
        )
        print(f"{reg:<25} {samples_with:>15} {avg_relevant:>20.1f}")

    return samples


def _generate_synthetic_protocols() -> list[dict]:
    """
    Generate small synthetic protocol excerpts that test specific regulatory
    coverage patterns. These are NOT meant to be realistic protocols — they are
    targeted test vectors for retrieval evaluation.
    """
    return [
        {
            "id": "SYNTH_CONSENT_FULL",
            "text": """
SECTION 7: INFORMED CONSENT PROCEDURES

7.1 Consent Process
All participants will provide written informed consent prior to any study procedures,
in accordance with 21 CFR Part 50 and 45 CFR Part 46 (the Common Rule). The consent
form includes a description of the study, expected duration, procedures to be followed,
risks and benefits, alternatives to participation, and a statement that participation
is voluntary and may be withdrawn at any time without penalty.

7.2 Vulnerable Populations
Additional safeguards are in place for pregnant women (Subpart B), prisoners (Subpart C),
and children (Subpart D) per 45 CFR Part 46. A legally authorized representative may
provide consent on behalf of individuals who lack capacity. Children aged 7-17 will
provide assent in addition to parental consent.

7.3 IRB Oversight
The protocol has been reviewed and approved by the institutional review board (IRB)
at the lead site. Continuing review will be conducted at least annually per 21 CFR Part 56.
Any protocol amendments require IRB approval before implementation. Expedited review
procedures apply to minimal-risk modifications per 56.110.

7.4 Data Management and Electronic Records
All electronic data capture systems comply with 21 CFR Part 11 requirements for
electronic records and electronic signatures. The eCRF system includes audit trails,
user access controls, password protections, and has undergone formal system validation.
Source data verification is performed against original medical records.
""",
        },
        {
            "id": "SYNTH_IND_SAFETY",
            "text": """
SECTION 10: SAFETY REPORTING AND IND REQUIREMENTS

10.1 Adverse Event Reporting
All adverse events (AEs) will be recorded from the time of first dose until 30 days
after the last dose. Serious adverse events (SAEs) must be reported to the sponsor
within 24 hours of the investigator becoming aware per 21 CFR 312.32.

10.2 IND Safety Reports
The sponsor will submit IND safety reports to the FDA for any suspected adverse reaction
that is both serious and unexpected, as defined by 21 CFR Part 312. Annual reports
per 312.33 will include a summary of safety information.

10.3 Data Safety Monitoring Board
An independent DSMB will review unblinded safety data every 6 months. The DSMB charter
defines stopping rules for unacceptable toxicity.

10.4 Drug Accountability
Investigational drug accountability logs will be maintained at each site. The investigator
is responsible for ensuring proper storage, dispensing, and return/destruction of unused
investigational product per the sponsor's instructions and IND requirements.
""",
        },
        {
            "id": "SYNTH_EMPTY_MINIMAL",
            "text": """
CLINICAL TRIAL PROTOCOL

Study Title: A Phase I Study of Drug X in Healthy Volunteers

1. OBJECTIVES
The primary objective is to evaluate the safety and tolerability of Drug X.

2. STUDY DESIGN
This is a randomized, double-blind, placebo-controlled study.
Approximately 30 subjects will be enrolled across 3 dose cohorts.

3. ELIGIBILITY
Healthy adults aged 18-55, no significant medical history.

4. ENDPOINTS
Primary: Incidence of treatment-emergent adverse events.
Secondary: Pharmacokinetic parameters (Cmax, AUC, t1/2).

5. STATISTICAL ANALYSIS
Descriptive statistics will summarize safety and PK data.
No formal hypothesis testing is planned for this Phase I study.
""",
        },
        {
            "id": "SYNTH_GLP_GMP",
            "text": """
SECTION 4: NONCLINICAL AND MANUFACTURING

4.1 Good Laboratory Practice Studies
All pivotal nonclinical studies were conducted in compliance with Good Laboratory Practice
(GLP) per 21 CFR Part 58. The study director ensured protocol adherence and the quality
assurance unit performed periodic inspections. Test article characterization and stability
were documented per 58.105.

4.2 Drug Manufacturing
The investigational drug product is manufactured under current Good Manufacturing Practice
(cGMP) conditions per 21 CFR Part 211. Batch records, in-process testing, and release
specifications are maintained. Stability testing supports the proposed shelf life.

4.3 Labeling
Investigational product labeling complies with 21 CFR 312.6 requirements, including
the statement "Caution: New Drug — Limited by Federal law to investigational use."
""",
        },
    ]


def main():
    parser = argparse.ArgumentParser(description="Generate ground truth for CLARA retrieval evaluation")
    parser.add_argument(
        "--protocols-dir", "-p",
        default="data/documents/compliant/parsed",
        help="Directory containing parsed protocol text files",
    )
    parser.add_argument(
        "--include-non-compliant", "-n",
        action="store_true",
        help="Also process non-compliant (redacted) protocol texts",
    )
    parser.add_argument(
        "--non-compliant-dir",
        default="data/documents/non_compliant/parsed",
        help="Directory containing parsed non-compliant protocol texts",
    )
    parser.add_argument(
        "--output", "-o",
        default="test/ground_truth/annotations.json",
        help="Output path for annotations JSON",
    )
    parser.add_argument("--limit", "-l", type=int, default=None)
    args = parser.parse_args()

    protocols_dir = Path(args.protocols_dir)
    nc_dir = Path(args.non_compliant_dir) if args.include_non_compliant else None
    output_path = Path(args.output)

    generate_ground_truth(protocols_dir, nc_dir, output_path, args.limit)


if __name__ == "__main__":
    main()
